export const products = [{
  "prod_name": "Paracetamol",
  "prod_date_expir": new Date("2029-09-16 06:23:34"),
  "prod_date_pack": new Date("2032-09-16 06:23:34"),
  "prod_status": "en espera",
  "prod_image": "http://192.168.83.44:5500/src/assets/carrousel-test/Paracetamol_10.png",
  "prod_brand": "FarmaciaPopular",
  "prod_price": 19904,
  "prod_description": "Cada medicamento contiene un principio activo específico",
  "prod_quantity": 79,
  "prod_tablet": "15 comprimidos",
  "prod_detail": "Paracetamol 10mg",
  "prod_category": "Antidepresivos",
  "prod_recipe": false
}, {
  "prod_name": "Ibuprofeno",
  "prod_date_expir": new Date("2027-07-11 01:19:12"),
  "prod_date_pack": new Date("2030-07-11 01:19:12"),
  "prod_status": "en espera",
  "prod_image": "http://192.168.83.44:5500/src/assets/carrousel-test/Ibuprofeno_10.png",
  "prod_brand": "FarmaciaExpress",
  "prod_price": 2248,
  "prod_description": "Cada medicamento contiene un principio activo específico",
  "prod_quantity": 99,
  "prod_tablet": "3 comprimidos",
  "prod_detail": "Ibuprofeno 10mg",
  "prod_category": "Antipiréticos",
  "prod_recipe": false
}, {
  "prod_name": "Amoxicilina",
  "prod_date_expir": new Date("2028-02-02 03:29:36"),
  "prod_date_pack": new Date("2031-02-02 03:29:36"),
  "prod_status": "disponible",
  "prod_image": "http://192.168.83.44:5500/src/assets/carrousel-test/Amoxicilina_10.png",
  "prod_brand": "SaludActiva",
  "prod_price": 29727,
  "prod_description": "Cada medicamento contiene un principio activo específico",
  "prod_quantity": 36,
  "prod_tablet": "11 comprimidos",
  "prod_detail": "Amoxicilina 10mg",
  "prod_category": "Antiinflamatorios",
  "prod_recipe": true
}, {
  "prod_name": "Omeprazol",
  "prod_date_expir": new Date("2030-05-08 12:33:58"),
  "prod_date_pack": new Date("2033-05-08 12:33:58"),
  "prod_status": "en espera",
  "prod_image": "http://192.168.83.44:5500/src/assets/carrousel-test/Omeprazol_10.png",
  "prod_brand": "BienestarFarm",
  "prod_price": 14938,
  "prod_description": "una sustancia responsable de producir el efecto terapéutico deseado en el organismo. Detallamos cuidadosamente el principio activo de cada producto para que los usuarios estén informados sobre la base científica de su acción.",
  "prod_quantity": 83,
  "prod_tablet": "13 comprimidos",
  "prod_detail": "Omeprazol 10mg",
  "prod_category": "Antihistamínicos",
  "prod_recipe": true
}, {
  "prod_name": "Loratadina",
  "prod_date_expir": new Date("2026-10-02 22:32:06"),
  "prod_date_pack": new Date("2029-10-02 22:32:06"),
  "prod_status": "en stock",
  "prod_image": "http://192.168.83.44:5500/src/assets/carrousel-test/Loratadina_10.png",
  "prod_brand": "SaludActiva",
  "prod_price": 2461,
  "prod_description": "Cada medicamento contiene un principio activo específico",
  "prod_quantity": 94,
  "prod_tablet": "2 comprimidos",
  "prod_detail": "Loratadina 10mg",
  "prod_category": "Antibióticos",
  "prod_recipe": true
}, {
  "prod_name": "Diazepam",
  "prod_date_expir": new Date("2027-10-29 21:39:48"),
  "prod_date_pack": new Date("2030-10-29 21:39:48"),
  "prod_status": "en stock",
  "prod_image": "http://192.168.83.44:5500/src/assets/carrousel-test/Diazepam_10.png",
  "prod_brand": "MediFarma",
  "prod_price": 28526,
  "prod_description": "una sustancia responsable de producir el efecto terapéutico deseado en el organismo. Detallamos cuidadosamente el principio activo de cada producto para que los usuarios estén informados sobre la base científica de su acción.",
  "prod_quantity": 52,
  "prod_tablet": "30 comprimidos",
  "prod_detail": "Diazepam 10mg",
  "prod_category": "Analgésicos",
  "prod_recipe": true
}, {
  "prod_name": "Ciprofloxacino",
  "prod_date_expir": new Date("2024-09-19 15:13:01"),
  "prod_date_pack": new Date("2027-09-19 15:13:01"),
  "prod_status": "en espera",
  "prod_image": "http://192.168.83.44:5500/src/assets/carrousel-test/Ciprofloxacino_10.png",
  "prod_brand": "VidaSana",
  "prod_price": 18854,
  "prod_description": "una sustancia responsable de producir el efecto terapéutico deseado en el organismo. Detallamos cuidadosamente el principio activo de cada producto para que los usuarios estén informados sobre la base científica de su acción.",
  "prod_quantity": 18,
  "prod_tablet": "20 comprimidos",
  "prod_detail": "Ciprofloxacino 10mg",
  "prod_category": "Antitusivos",
  "prod_recipe": true
}, {
  "prod_name": "Metformina",
  "prod_date_expir": new Date("2029-06-14 10:32:31"),
  "prod_date_pack": new Date("2032-06-14 10:32:31"),
  "prod_status": "agotado",
  "prod_image": "http://192.168.83.44:5500/src/assets/carrousel-test/Metformina_10.png",
  "prod_brand": "MediFarma",
  "prod_price": 12848,
  "prod_description": "Cada medicamento contiene un principio activo específico",
  "prod_quantity": 52,
  "prod_tablet": "11 comprimidos",
  "prod_detail": "Metformina 10mg",
  "prod_category": "Antidiarreicos",
  "prod_recipe": false
}, {
  "prod_name": "Atorvastatina",
  "prod_date_expir": new Date("2024-01-09 03:49:47"),
  "prod_date_pack": new Date("2027-01-09 03:49:47"),
  "prod_status": "en stock",
  "prod_image": "http://192.168.83.44:5500/src/assets/carrousel-test/Atorvastatina_10.png",
  "prod_brand": "MediFarma",
  "prod_price": 19698,
  "prod_description": "Cada medicamento contiene un principio activo específico",
  "prod_quantity": 55,
  "prod_tablet": "18 comprimidos",
  "prod_detail": "Atorvastatina 10mg",
  "prod_category": "Antiinflamatorios",
  "prod_recipe": true
}, {
  "prod_name": "Clonazepam",
  "prod_date_expir": new Date("2030-05-07 05:37:37"),
  "prod_date_pack": new Date("2033-05-07 05:37:37"),
  "prod_status": "agotado",
  "prod_image": "http://192.168.83.44:5500/src/assets/carrousel-test/Clonazepam_10.png",
  "prod_brand": "SaludTotal",
  "prod_price": 22775,
  "prod_description": "Cada medicamento contiene un principio activo específico",
  "prod_quantity": 24,
  "prod_tablet": "21 comprimidos",
  "prod_detail": "Clonazepam 10mg",
  "prod_category": "Anticonceptivos",
  "prod_recipe": true
}]

export default products;